### ISSUE TITLE
[BUG] link to firefox extension is broken

### ISSUE THREAD

**Issue by sidoruk-sv** [wix-playground/wix-meido-improver#2]
https://addons.mozilla.org/firefox/downloads/file/2927617/wix_meido_improver-1.0.0-fx.xpi gives `We're sorry, but we can't find what you're looking for.`

**Comment by ghost** [comment]
Hi! Thank you for reporting the bug! I removed the link cause it was available only to me 🤦‍♂️
I will upload new versions to #wix-kyiv-crew slack channel.
