### ISSUE TITLE
[BUG] Corrupted symbols for prev/next buttons

### ISSUE THREAD

**Issue by sidoruk-sv** [wix-playground/wix-meido-improver#7]
https://take.ms/giWR5

Seems like it was committed already corrupted: 
https://github.com/wix-playground/wix-meido-improver/commit/41dfa2621bac6b99d4a0d94ca0f1135ff09d461d

https://github.com/wix-playground/wix-meido-improver/blob/master/extension/src/popup/page.html#L12

Symbols `<` `>` would be ok there.

**Comment by ghost** [comment]
Hi! Thanks for reporting! Will fix.
